### ISSUE TITLE
Add Cross-browser compatibility

### ISSUE THREAD

**Issue by K-mikaZ** [claustromaniac/etag-stoppa#10]
Tip To Make Your Code Compatible With All Browsers:
add `window.browser = window.msBrowser || window.browser || window.chrome;` // Cross-browser compatibility

This code was test (into developper mode) on ungoogled-chromium, vivaldi and firefox and works like a charm
```
window.browser = window.msBrowser || window.browser || window.chrome;
eTagFilter: function eTagFilter(d) {
    if (!d.responseHeaders) return {};
    const newHeaders = d.responseHeaders.filter(e => "etag" !== e.name.toLowerCase());
    return newHeaders.length < d.responseHeaders.length ? (console.log(`Removed ETag from request #${d.requestId}\n\t${d.url}`), { responseHeaders: newHeaders }) : void 0
}
browser.webRequest.onHeadersReceived.addListener(
    eTagFilter, {
        urls: ["<all_urls>"]
    },
    ["blocking", "responseHeaders"]
);
```

And into `manifest.json`
"description": "Prevents `browsers` from storing entity tags by removing ETag response headers unconditionally and without exceptions."

**Comment by r-a-y** [comment]
Actually, just changing `browser.webRequest` to `chrome.webRequest` will still work with Firefox as Firefox automatically recognizes `chrome` as `browser`.

See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension#api_namespace
