### ISSUE TITLE
meet.google.com breakage when removing ETag

### ISSUE THREAD

**Issue by crssi** [claustromaniac/etag-stoppa#9]
STR:
Join a google meeting meeting with ETag-stoppa enabled and the screen is blank, no video, no share screen, no chat, no controls.
Join a google meeting meeting with ETag-stoppa disabled and everything works.

Cheers

**Comment by eric15342335** [comment]
I don't see there's a breakage in my google meeting. you need to provide more information

**Comment by crssi** [comment]
At that time there was a Firefox version 83.
I have retested the same today and I also cannot reproduce anymore.

In the test conducted... that is plain vanilla profile and only ETag-stoppa extension installed, the only change is that Firefox is not the version 83 being at the time this issue was opened, but now it is version 85.

Conclusion would be that the problem was in the FIrefox and not extension, since now (being the only  difference is the FF version) the problem cannot be reproduced anymore.

Cheers

**Comment by eric15342335** [comment]
glad to hear it
